### ISSUE TITLE
More info in README

### ISSUE THREAD

**Issue by tim-hilt** [TornaxO7/tree-setter#1]
Hi there! I basically [requested exactly this project over on Reddit](https://reddit.com/r/neovim/comments/sftfl8/automatically_add_semicolon_to_end_of_line/) and am very thankful, that a user has guided me to this project of yours! :)

I have some questions though, that are not answered in the README:

- Why did you start this project?
- How does treesitter behave, if it parses incorrect source-code?
- Why does this only work for C right now?
- Do you know of any cross-language alternatives to this project?

Thank you for creating this!

**Comment by TornaxO7** [comment]
Damn, that was unexpected to get an issue for this, but I'm happy to get one :)

> Why did you start this project?

<details>

**Short version**
I wanted a automatic semicolon/comma setter as well. Since I couldn't find one, I started to develop my own one.

**Longer version**
Well at the time when I created this module, I was coding in C a lot. So I was wondering if there is a plugin which could automatically place the semicolons/commas etc. for me. The only plugin which I could find was [cosco.vim](https://github.com/lfilho/cosco.vim) but it couldn't place the stuff automatically. So I created a [fork](https://github.com/TornaxO7/auto-cosco.vim) and tried it on my own with vimscript. But the more cases I covered, the more problems came up (like the order of checking which character should be places). Than I tried to learn how to work with treesitter and though that it might be easier to use treesitter for that and that's how I started this plugin. But after some time again, I got some conflicts with the queries (more in your next question) and so... I stopped here as well.... and thought to move back to `auto-cosco` but to think to apply all possible cases in `if` conditions with a long `regex`-string wasn't nice, so I stopped developing there as well....

</details>

> How does treesitter behave, if it parses incorrect source-code?

<details>

**Short version**
When I was still developing on this plugin, treesitter behaved (sometimes) differently for the same error.

**Long version**
This is the part why I stopped developing this plugin. The first "errors" where pretty easy, since treesitter parsed them like [here](https://github.com/TornaxO7/tree-setter/blob/master/CONTRIBUTING.md#weird-queries). But the problem was, that treesitter parsed the error-code in different ways, when I resarted neovim. So I couldn't create a query for each case, I'd need to create multiple queries for some cases which would be harder to maintain, since some queries started to block the other queries...

</details>

> Why does this only work for C right now?

<details>

When I started to create this plugin, only C was really easy to write queries for. I tried other languages as well like `rust` but the problem there was just, that treesitter was missing a lot of information, if the source code wasn't complete. So I couldn't create suitable queries for that.

</details>

> Do you know of any cross-language alternatives to this project?

<details>

The only plugin I know is [cosco.vim](https://github.com/lfilho/cosco.vim) which is still actively maintained, but it doesn't have an auto-setting option as far as I know.

</details>

**NOTE:**
I didn't apply any changes for a long time now, so there might be actually some improvement in treesitter which might have solved some of those issues which I named, but I haven't tried my queries again since my last commit here.

**Comment by tim-hilt** [comment]
Thanks for the thorough answers to my questions! I hope that this project is going to become more general and more mature. I currently don’t really know about treesitter queries, but I will look into it and maybe contribute at the Java-side of things :)

**Comment by TornaxO7** [comment]
No problem! c(^-^)c You're welcome
